services:
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: unless-stopped
    networks: 
        - cloud
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    networks: 
      - cloud
    ports:
      - 8096:8096
    environment:
      - TZ=America/Montreal
    volumes:
      - jellyfin_data:/config
      - /mnt/media/Movies:/movies
      - /mnt/media/TV:/tv

  backend:
    image: nadch4/tp-final-2283110-homebreeze-backend:v1
    build:
      context: ./tp-final-infornuage-2283110-backend
    container_name: backend
    ports:
      - "9696:9696"
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=backend
      - SERVER_PORT=9696
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/home_breeze_bd
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    networks:
      - cloud
 
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=home_breeze_bd
    networks:
      - cloud
    volumes:
      - db:/data/db
      - ./db-seed:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
 
  frontend:
    image: nadch4/tp-final-2283110-homebreeze-frontend:v1
    build:
      context: ./tp-final-infornuage-2283110-frontend
    ports:
      - "9292:9292"
    depends_on:
      - backend
    networks:
      - cloud
volumes:
  portainer_data:
  jellyfin_data:
  db:
 
networks:
  cloud:
    driver: bridge